name: "Terraform Bootstrap - Dev"

on:
  push:
    paths:
      - 'envs/dev/**'
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform Plan & Apply - Dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/852007451930/locations/global/workloadIdentityPools/github-pool-naresh'
          service_account: 'terraform-dev-sa@naresh-dev-456511.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform -chdir=envs/dev init

      - name: Terraform Plan
        run: terraform -chdir=envs/dev plan

      - name: Terraform Apply
        run: terraform -chdir=envs/dev apply -auto-approve
